<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240612061140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE hurtowe_zamowienia_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE hurtowe_zamowienia (id INT NOT NULL, kompozycja1_id INT DEFAULT NULL, kompozycja2_id INT DEFAULT NULL, kompozycja3_id INT DEFAULT NULL, kompozycja4_id INT DEFAULT NULL, kompozycja5_id INT DEFAULT NULL, kompozycja6_id INT DEFAULT NULL, kompozycja7_id INT DEFAULT NULL, kompozycja8_id INT DEFAULT NULL, kompozycja9_id INT DEFAULT NULL, kompozycja10_id INT DEFAULT NULL, kompozycja11_id INT DEFAULT NULL, kompozycja12_id INT DEFAULT NULL, kompozycja13_id INT DEFAULT NULL, kompozycja14_id INT DEFAULT NULL, kompozycja15_id INT DEFAULT NULL, kompozycja16_id INT DEFAULT NULL, kompozycja17_id INT DEFAULT NULL, kompozycja18_id INT DEFAULT NULL, kompozycja19_id INT DEFAULT NULL, kompozycja20_id INT DEFAULT NULL, kompozycja21_id INT DEFAULT NULL, kompozycja22_id INT DEFAULT NULL, kompozycja23_id INT DEFAULT NULL, kompozycja24_id INT DEFAULT NULL, kompozycja25_id INT DEFAULT NULL, kompozycja26_id INT DEFAULT NULL, kompozycja27_id INT DEFAULT NULL, kompozycja28_id INT DEFAULT NULL, kompozycja29_id INT DEFAULT NULL, kompozycja30_id INT DEFAULT NULL, kompozycja31_id INT DEFAULT NULL, kompozycja32_id INT DEFAULT NULL, kompozycja33_id INT DEFAULT NULL, kompozycja34_id INT DEFAULT NULL, kompozycja35_id INT DEFAULT NULL, kompozycja36_id INT DEFAULT NULL, kompozycja37_id INT DEFAULT NULL, kompozycja38_id INT DEFAULT NULL, kompozycja39_id INT DEFAULT NULL, kompozycja40_id INT DEFAULT NULL, kontrahent_id INT DEFAULT NULL, sztuk1 INT DEFAULT NULL, cena1 DOUBLE PRECISION DEFAULT NULL, wartosc1 DOUBLE PRECISION DEFAULT NULL, wozek1 INT DEFAULT NULL, nazwa VARCHAR(255) DEFAULT NULL, nazwa1 VARCHAR(255) DEFAULT NULL, sztuk2 INT DEFAULT NULL, cena2 DOUBLE PRECISION DEFAULT NULL, wartosc2 DOUBLE PRECISION DEFAULT NULL, wozek2 INT DEFAULT NULL, nazwa2 VARCHAR(255) DEFAULT NULL, sztuk3 INT DEFAULT NULL, cena3 DOUBLE PRECISION DEFAULT NULL, wartosc3 DOUBLE PRECISION DEFAULT NULL, wozek3 INT DEFAULT NULL, nazwa3 VARCHAR(255) DEFAULT NULL, sztuk4 INT DEFAULT NULL, cena4 DOUBLE PRECISION DEFAULT NULL, wartosc4 DOUBLE PRECISION DEFAULT NULL, wozek4 INT DEFAULT NULL, nazwa4 VARCHAR(255) DEFAULT NULL, sztuk5 INT DEFAULT NULL, cena5 DOUBLE PRECISION DEFAULT NULL, wartosc5 DOUBLE PRECISION DEFAULT NULL, wozek5 INT DEFAULT NULL, nazwa5 VARCHAR(255) DEFAULT NULL, sztuk6 INT DEFAULT NULL, cena6 DOUBLE PRECISION DEFAULT NULL, wartosc6 DOUBLE PRECISION DEFAULT NULL, wozek6 INT DEFAULT NULL, nazwa6 VARCHAR(255) DEFAULT NULL, sztuk7 INT DEFAULT NULL, cena7 DOUBLE PRECISION DEFAULT NULL, wartosc7 DOUBLE PRECISION DEFAULT NULL, wozek7 INT DEFAULT NULL, nazwa7 VARCHAR(255) DEFAULT NULL, sztuk8 INT DEFAULT NULL, cena8 DOUBLE PRECISION DEFAULT NULL, wartosc8 DOUBLE PRECISION DEFAULT NULL, wozek8 INT DEFAULT NULL, nazwa8 VARCHAR(255) DEFAULT NULL, sztuk9 INT DEFAULT NULL, cena9 DOUBLE PRECISION DEFAULT NULL, wartosc9 DOUBLE PRECISION DEFAULT NULL, wozek9 INT DEFAULT NULL, nazwa9 VARCHAR(255) DEFAULT NULL, sztuk10 INT DEFAULT NULL, cena10 DOUBLE PRECISION DEFAULT NULL, wartosc10 DOUBLE PRECISION DEFAULT NULL, wozek10 INT DEFAULT NULL, nazwa10 VARCHAR(255) DEFAULT NULL, sztuk11 INT DEFAULT NULL, cena11 DOUBLE PRECISION DEFAULT NULL, wartosc11 DOUBLE PRECISION DEFAULT NULL, wozek11 INT DEFAULT NULL, nazwa11 VARCHAR(255) DEFAULT NULL, sztuk12 INT DEFAULT NULL, cena12 DOUBLE PRECISION DEFAULT NULL, wartosc12 DOUBLE PRECISION DEFAULT NULL, wozek12 INT DEFAULT NULL, nazwa12 VARCHAR(255) DEFAULT NULL, sztuk13 INT DEFAULT NULL, cena13 DOUBLE PRECISION DEFAULT NULL, wartosc13 DOUBLE PRECISION DEFAULT NULL, wozek13 INT DEFAULT NULL, nazwa13 VARCHAR(255) DEFAULT NULL, sztuk14 INT DEFAULT NULL, cena14 DOUBLE PRECISION DEFAULT NULL, wartosc14 DOUBLE PRECISION DEFAULT NULL, wozek14 INT DEFAULT NULL, nazwa14 VARCHAR(255) DEFAULT NULL, sztuk15 INT DEFAULT NULL, cena15 DOUBLE PRECISION DEFAULT NULL, wartosc15 DOUBLE PRECISION DEFAULT NULL, wozek15 INT DEFAULT NULL, nazwa15 VARCHAR(255) DEFAULT NULL, sztuk16 INT DEFAULT NULL, cena16 DOUBLE PRECISION DEFAULT NULL, wartosc16 DOUBLE PRECISION DEFAULT NULL, wozek16 INT DEFAULT NULL, nazwa16 VARCHAR(255) DEFAULT NULL, sztuk17 INT DEFAULT NULL, cena17 DOUBLE PRECISION DEFAULT NULL, wartosc17 DOUBLE PRECISION DEFAULT NULL, wozek17 INT DEFAULT NULL, nazwa17 VARCHAR(255) DEFAULT NULL, sztuk18 INT DEFAULT NULL, cena18 DOUBLE PRECISION DEFAULT NULL, wartosc18 DOUBLE PRECISION DEFAULT NULL, wozek18 INT DEFAULT NULL, nazwa18 VARCHAR(255) DEFAULT NULL, sztuk19 INT DEFAULT NULL, cena19 DOUBLE PRECISION DEFAULT NULL, wartosc19 DOUBLE PRECISION DEFAULT NULL, wozek19 INT DEFAULT NULL, nazwa19 VARCHAR(255) DEFAULT NULL, sztuk20 INT DEFAULT NULL, cena20 DOUBLE PRECISION DEFAULT NULL, wartosc20 DOUBLE PRECISION DEFAULT NULL, wozek20 INT DEFAULT NULL, nazwa20 VARCHAR(255) DEFAULT NULL, sztuk21 INT DEFAULT NULL, cena21 DOUBLE PRECISION DEFAULT NULL, wartosc21 DOUBLE PRECISION DEFAULT NULL, wozek21 INT DEFAULT NULL, nazwa21 VARCHAR(255) DEFAULT NULL, sztuk22 INT DEFAULT NULL, cena22 DOUBLE PRECISION DEFAULT NULL, wartosc22 DOUBLE PRECISION DEFAULT NULL, wozek22 INT DEFAULT NULL, nazwa22 VARCHAR(255) DEFAULT NULL, sztuk23 INT DEFAULT NULL, cena23 DOUBLE PRECISION DEFAULT NULL, wartosc23 DOUBLE PRECISION DEFAULT NULL, wozek23 INT DEFAULT NULL, nazwa23 VARCHAR(255) DEFAULT NULL, sztuk24 INT DEFAULT NULL, cena24 DOUBLE PRECISION DEFAULT NULL, wartosc24 DOUBLE PRECISION DEFAULT NULL, wozek24 INT DEFAULT NULL, nazwa24 VARCHAR(255) DEFAULT NULL, sztuk25 INT DEFAULT NULL, cena25 DOUBLE PRECISION DEFAULT NULL, wartosc25 DOUBLE PRECISION DEFAULT NULL, wozek25 INT DEFAULT NULL, nazwa25 VARCHAR(255) DEFAULT NULL, sztuk26 INT DEFAULT NULL, cena26 DOUBLE PRECISION DEFAULT NULL, wartosc26 DOUBLE PRECISION DEFAULT NULL, wozek26 INT DEFAULT NULL, nazwa26 VARCHAR(255) DEFAULT NULL, sztuk27 INT DEFAULT NULL, cena27 DOUBLE PRECISION DEFAULT NULL, wartosc27 DOUBLE PRECISION DEFAULT NULL, wozek27 INT DEFAULT NULL, nazwa27 VARCHAR(255) DEFAULT NULL, sztuk28 INT DEFAULT NULL, cena28 DOUBLE PRECISION DEFAULT NULL, wartosc28 DOUBLE PRECISION DEFAULT NULL, wozek28 INT DEFAULT NULL, nazwa28 VARCHAR(255) DEFAULT NULL, sztuk29 INT DEFAULT NULL, cena29 DOUBLE PRECISION DEFAULT NULL, wartosc29 DOUBLE PRECISION DEFAULT NULL, wozek29 INT DEFAULT NULL, nazwa29 VARCHAR(255) DEFAULT NULL, sztuk30 INT DEFAULT NULL, cena30 DOUBLE PRECISION DEFAULT NULL, wartosc30 DOUBLE PRECISION DEFAULT NULL, wozek30 INT DEFAULT NULL, nazwa30 VARCHAR(255) DEFAULT NULL, sztuk31 INT DEFAULT NULL, cena31 DOUBLE PRECISION DEFAULT NULL, wartosc31 DOUBLE PRECISION DEFAULT NULL, wozek31 INT DEFAULT NULL, nazwa31 VARCHAR(255) DEFAULT NULL, sztuk32 INT DEFAULT NULL, cena32 DOUBLE PRECISION DEFAULT NULL, wartosc32 DOUBLE PRECISION DEFAULT NULL, wozek32 INT DEFAULT NULL, nazwa32 VARCHAR(255) DEFAULT NULL, sztuk33 INT DEFAULT NULL, cena33 DOUBLE PRECISION DEFAULT NULL, wartosc33 DOUBLE PRECISION DEFAULT NULL, wozek33 INT DEFAULT NULL, nazwa33 VARCHAR(255) DEFAULT NULL, sztuk34 INT DEFAULT NULL, cena34 DOUBLE PRECISION DEFAULT NULL, wartosc34 DOUBLE PRECISION DEFAULT NULL, wozek34 INT DEFAULT NULL, nazwa34 VARCHAR(255) DEFAULT NULL, sztuk35 INT DEFAULT NULL, cena35 DOUBLE PRECISION DEFAULT NULL, wartosc35 DOUBLE PRECISION DEFAULT NULL, wozek35 INT DEFAULT NULL, nazwa35 VARCHAR(255) DEFAULT NULL, sztuk36 INT DEFAULT NULL, cena36 DOUBLE PRECISION DEFAULT NULL, wartosc36 DOUBLE PRECISION DEFAULT NULL, wozek36 INT DEFAULT NULL, nazwa36 VARCHAR(255) DEFAULT NULL, sztuk37 INT DEFAULT NULL, cena37 DOUBLE PRECISION DEFAULT NULL, wartosc37 DOUBLE PRECISION DEFAULT NULL, wozek37 INT DEFAULT NULL, nazwa37 VARCHAR(255) DEFAULT NULL, sztuk38 INT DEFAULT NULL, cena38 DOUBLE PRECISION DEFAULT NULL, wartosc38 DOUBLE PRECISION DEFAULT NULL, wozek38 INT DEFAULT NULL, nazwa38 VARCHAR(255) DEFAULT NULL, sztuk39 INT DEFAULT NULL, cena39 DOUBLE PRECISION DEFAULT NULL, wartosc39 DOUBLE PRECISION DEFAULT NULL, wozek39 INT DEFAULT NULL, nazwa39 VARCHAR(255) DEFAULT NULL, sztuk40 INT DEFAULT NULL, cena40 DOUBLE PRECISION DEFAULT NULL, wartosc40 DOUBLE PRECISION DEFAULT NULL, wozek40 INT DEFAULT NULL, nazwa40 VARCHAR(255) DEFAULT NULL, suma DOUBLE PRECISION DEFAULT NULL, rodzaj1 VARCHAR(255) DEFAULT NULL, rodzaj2 VARCHAR(255) DEFAULT NULL, rodzaj3 VARCHAR(255) DEFAULT NULL, rodzaj4 VARCHAR(255) DEFAULT NULL, rodzaj5 VARCHAR(255) DEFAULT NULL, rodzaj6 VARCHAR(255) DEFAULT NULL, rodzaj7 VARCHAR(255) DEFAULT NULL, rodzaj8 VARCHAR(255) DEFAULT NULL, rodzaj9 VARCHAR(255) DEFAULT NULL, rodzaj10 VARCHAR(255) DEFAULT NULL, rodzaj11 VARCHAR(255) DEFAULT NULL, rodzaj12 VARCHAR(255) DEFAULT NULL, rodzaj13 VARCHAR(255) DEFAULT NULL, rodzaj14 VARCHAR(255) DEFAULT NULL, rodzaj15 VARCHAR(255) DEFAULT NULL, rodzaj16 VARCHAR(255) DEFAULT NULL, rodzaj17 VARCHAR(255) DEFAULT NULL, rodzaj18 VARCHAR(255) DEFAULT NULL, rodzaj19 VARCHAR(255) DEFAULT NULL, rodzaj20 VARCHAR(255) DEFAULT NULL, rodzaj21 VARCHAR(255) DEFAULT NULL, rodzaj22 VARCHAR(255) DEFAULT NULL, rodzaj23 VARCHAR(255) DEFAULT NULL, rodzaj24 VARCHAR(255) DEFAULT NULL, rodzaj25 VARCHAR(255) DEFAULT NULL, rodzaj26 VARCHAR(255) DEFAULT NULL, rodzaj27 VARCHAR(255) DEFAULT NULL, rodzaj28 VARCHAR(255) DEFAULT NULL, rodzaj29 VARCHAR(255) DEFAULT NULL, rodzaj30 VARCHAR(255) DEFAULT NULL, rodzaj31 VARCHAR(255) DEFAULT NULL, rodzaj32 VARCHAR(255) DEFAULT NULL, rodzaj33 VARCHAR(255) DEFAULT NULL, rodzaj34 VARCHAR(255) DEFAULT NULL, rodzaj35 VARCHAR(255) DEFAULT NULL, rodzaj36 VARCHAR(255) DEFAULT NULL, rodzaj37 VARCHAR(255) DEFAULT NULL, rodzaj38 VARCHAR(255) DEFAULT NULL, rodzaj39 VARCHAR(255) DEFAULT NULL, rodzaj40 VARCHAR(255) DEFAULT NULL, fv BOOLEAN DEFAULT NULL, uwagi TEXT DEFAULT NULL, fv_wystawiono TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4B59900CE388C62F ON hurtowe_zamowienia (kompozycja1_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CF13D69C1 ON hurtowe_zamowienia (kompozycja2_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C49810EA4 ON hurtowe_zamowienia (kompozycja3_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CD456361D ON hurtowe_zamowienia (kompozycja4_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C6CEA5178 ON hurtowe_zamowienia (kompozycja5_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C7E5FFE96 ON hurtowe_zamowienia (kompozycja6_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CC6E399F3 ON hurtowe_zamowienia (kompozycja7_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C9E8089A5 ON hurtowe_zamowienia (kompozycja8_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C263CEEC0 ON hurtowe_zamowienia (kompozycja9_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CC5E2FF69 ON hurtowe_zamowienia (kompozycja10_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C7D5E980C ON hurtowe_zamowienia (kompozycja11_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C6FEB37E2 ON hurtowe_zamowienia (kompozycja12_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CD7575087 ON hurtowe_zamowienia (kompozycja13_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C4A80683E ON hurtowe_zamowienia (kompozycja14_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CF23C0F5B ON hurtowe_zamowienia (kompozycja15_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CE089A0B5 ON hurtowe_zamowienia (kompozycja16_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C5835C7D0 ON hurtowe_zamowienia (kompozycja17_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C56D786 ON hurtowe_zamowienia (kompozycja18_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CB8EAB0E3 ON hurtowe_zamowienia (kompozycja19_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C824285B9 ON hurtowe_zamowienia (kompozycja20_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C3AFEE2DC ON hurtowe_zamowienia (kompozycja21_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C284B4D32 ON hurtowe_zamowienia (kompozycja22_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C90F72A57 ON hurtowe_zamowienia (kompozycja23_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CD2012EE ON hurtowe_zamowienia (kompozycja24_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CB59C758B ON hurtowe_zamowienia (kompozycja25_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CA729DA65 ON hurtowe_zamowienia (kompozycja26_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C1F95BD00 ON hurtowe_zamowienia (kompozycja27_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C47F6AD56 ON hurtowe_zamowienia (kompozycja28_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CFF4ACA33 ON hurtowe_zamowienia (kompozycja29_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CBF22AC09 ON hurtowe_zamowienia (kompozycja30_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C79ECB6C ON hurtowe_zamowienia (kompozycja31_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C152B6482 ON hurtowe_zamowienia (kompozycja32_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CAD9703E7 ON hurtowe_zamowienia (kompozycja33_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C30403B5E ON hurtowe_zamowienia (kompozycja34_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C88FC5C3B ON hurtowe_zamowienia (kompozycja35_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C9A49F3D5 ON hurtowe_zamowienia (kompozycja36_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C22F594B0 ON hurtowe_zamowienia (kompozycja37_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C7A9684E6 ON hurtowe_zamowienia (kompozycja38_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CC22AE383 ON hurtowe_zamowienia (kompozycja39_id)');
        $this->addSql('CREATE INDEX IDX_4B59900CD027019 ON hurtowe_zamowienia (kompozycja40_id)');
        $this->addSql('CREATE INDEX IDX_4B59900C38A37D02 ON hurtowe_zamowienia (kontrahent_id)');
        $this->addSql('COMMENT ON COLUMN hurtowe_zamowienia.fv_wystawiono IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CE388C62F FOREIGN KEY (kompozycja1_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CF13D69C1 FOREIGN KEY (kompozycja2_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C49810EA4 FOREIGN KEY (kompozycja3_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CD456361D FOREIGN KEY (kompozycja4_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C6CEA5178 FOREIGN KEY (kompozycja5_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C7E5FFE96 FOREIGN KEY (kompozycja6_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CC6E399F3 FOREIGN KEY (kompozycja7_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C9E8089A5 FOREIGN KEY (kompozycja8_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C263CEEC0 FOREIGN KEY (kompozycja9_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CC5E2FF69 FOREIGN KEY (kompozycja10_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C7D5E980C FOREIGN KEY (kompozycja11_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C6FEB37E2 FOREIGN KEY (kompozycja12_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CD7575087 FOREIGN KEY (kompozycja13_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C4A80683E FOREIGN KEY (kompozycja14_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CF23C0F5B FOREIGN KEY (kompozycja15_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CE089A0B5 FOREIGN KEY (kompozycja16_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C5835C7D0 FOREIGN KEY (kompozycja17_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C56D786 FOREIGN KEY (kompozycja18_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CB8EAB0E3 FOREIGN KEY (kompozycja19_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C824285B9 FOREIGN KEY (kompozycja20_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C3AFEE2DC FOREIGN KEY (kompozycja21_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C284B4D32 FOREIGN KEY (kompozycja22_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C90F72A57 FOREIGN KEY (kompozycja23_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CD2012EE FOREIGN KEY (kompozycja24_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CB59C758B FOREIGN KEY (kompozycja25_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CA729DA65 FOREIGN KEY (kompozycja26_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C1F95BD00 FOREIGN KEY (kompozycja27_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C47F6AD56 FOREIGN KEY (kompozycja28_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CFF4ACA33 FOREIGN KEY (kompozycja29_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CBF22AC09 FOREIGN KEY (kompozycja30_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C79ECB6C FOREIGN KEY (kompozycja31_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C152B6482 FOREIGN KEY (kompozycja32_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CAD9703E7 FOREIGN KEY (kompozycja33_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C30403B5E FOREIGN KEY (kompozycja34_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C88FC5C3B FOREIGN KEY (kompozycja35_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C9A49F3D5 FOREIGN KEY (kompozycja36_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C22F594B0 FOREIGN KEY (kompozycja37_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C7A9684E6 FOREIGN KEY (kompozycja38_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CC22AE383 FOREIGN KEY (kompozycja39_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900CD027019 FOREIGN KEY (kompozycja40_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia ADD CONSTRAINT FK_4B59900C38A37D02 FOREIGN KEY (kontrahent_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE hurtowe_zamowienia_id_seq CASCADE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CE388C62F');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CF13D69C1');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C49810EA4');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CD456361D');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C6CEA5178');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C7E5FFE96');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CC6E399F3');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C9E8089A5');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C263CEEC0');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CC5E2FF69');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C7D5E980C');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C6FEB37E2');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CD7575087');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C4A80683E');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CF23C0F5B');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CE089A0B5');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C5835C7D0');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C56D786');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CB8EAB0E3');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C824285B9');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C3AFEE2DC');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C284B4D32');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C90F72A57');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CD2012EE');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CB59C758B');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CA729DA65');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C1F95BD00');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C47F6AD56');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CFF4ACA33');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CBF22AC09');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C79ECB6C');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C152B6482');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CAD9703E7');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C30403B5E');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C88FC5C3B');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C9A49F3D5');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C22F594B0');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C7A9684E6');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CC22AE383');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900CD027019');
        $this->addSql('ALTER TABLE hurtowe_zamowienia DROP CONSTRAINT FK_4B59900C38A37D02');
        $this->addSql('DROP TABLE hurtowe_zamowienia');
    }
}
