<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230718154304 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja25_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja26_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja27_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja28_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja29_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja30_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja31_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja32_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja33_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja34_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja35_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja36_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja37_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja38_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja39_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD kompozycja40_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk25 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena25 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc25 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek25 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa25 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk26 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena26 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc26 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek26 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa26 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk27 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena27 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc27 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek27 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa27 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk28 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena28 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc28 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek28 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa28 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk29 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena29 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc29 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek29 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa29 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk30 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena30 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc30 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek30 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa30 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk31 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena31 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc31 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek31 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa31 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk32 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena32 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc32 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek32 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa32 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk33 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena33 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc33 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek33 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa33 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk34 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena34 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc34 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek34 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa34 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk35 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena35 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc35 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek35 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa35 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk36 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena36 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc36 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek36 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa36 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk37 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena37 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc37 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek37 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa37 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk38 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena38 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc38 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek38 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa38 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk39 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena39 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc39 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek39 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa39 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD sztuk40 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD cena40 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wartosc40 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD wozek40 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD nazwa40 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B83311B59C758B FOREIGN KEY (kompozycja25_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B83311A729DA65 FOREIGN KEY (kompozycja26_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B833111F95BD00 FOREIGN KEY (kompozycja27_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B8331147F6AD56 FOREIGN KEY (kompozycja28_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B83311FF4ACA33 FOREIGN KEY (kompozycja29_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B83311BF22AC09 FOREIGN KEY (kompozycja30_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B8331179ECB6C FOREIGN KEY (kompozycja31_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B83311152B6482 FOREIGN KEY (kompozycja32_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B83311AD9703E7 FOREIGN KEY (kompozycja33_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B8331130403B5E FOREIGN KEY (kompozycja34_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B8331188FC5C3B FOREIGN KEY (kompozycja35_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B833119A49F3D5 FOREIGN KEY (kompozycja36_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B8331122F594B0 FOREIGN KEY (kompozycja37_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B833117A9684E6 FOREIGN KEY (kompozycja38_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B83311C22AE383 FOREIGN KEY (kompozycja39_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hurtowe ADD CONSTRAINT FK_7B83311D027019 FOREIGN KEY (kompozycja40_id) REFERENCES wyceny (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B83311B59C758B ON hurtowe (kompozycja25_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B83311A729DA65 ON hurtowe (kompozycja26_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B833111F95BD00 ON hurtowe (kompozycja27_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B8331147F6AD56 ON hurtowe (kompozycja28_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B83311FF4ACA33 ON hurtowe (kompozycja29_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B83311BF22AC09 ON hurtowe (kompozycja30_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B8331179ECB6C ON hurtowe (kompozycja31_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B83311152B6482 ON hurtowe (kompozycja32_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B83311AD9703E7 ON hurtowe (kompozycja33_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B8331130403B5E ON hurtowe (kompozycja34_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B8331188FC5C3B ON hurtowe (kompozycja35_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B833119A49F3D5 ON hurtowe (kompozycja36_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B8331122F594B0 ON hurtowe (kompozycja37_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B833117A9684E6 ON hurtowe (kompozycja38_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B83311C22AE383 ON hurtowe (kompozycja39_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B83311D027019 ON hurtowe (kompozycja40_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B83311B59C758B');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B83311A729DA65');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B833111F95BD00');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B8331147F6AD56');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B83311FF4ACA33');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B83311BF22AC09');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B8331179ECB6C');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B83311152B6482');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B83311AD9703E7');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B8331130403B5E');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B8331188FC5C3B');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B833119A49F3D5');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B8331122F594B0');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B833117A9684E6');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B83311C22AE383');
        $this->addSql('ALTER TABLE hurtowe DROP CONSTRAINT FK_7B83311D027019');
        $this->addSql('DROP INDEX UNIQ_7B83311B59C758B');
        $this->addSql('DROP INDEX UNIQ_7B83311A729DA65');
        $this->addSql('DROP INDEX UNIQ_7B833111F95BD00');
        $this->addSql('DROP INDEX UNIQ_7B8331147F6AD56');
        $this->addSql('DROP INDEX UNIQ_7B83311FF4ACA33');
        $this->addSql('DROP INDEX UNIQ_7B83311BF22AC09');
        $this->addSql('DROP INDEX UNIQ_7B8331179ECB6C');
        $this->addSql('DROP INDEX UNIQ_7B83311152B6482');
        $this->addSql('DROP INDEX UNIQ_7B83311AD9703E7');
        $this->addSql('DROP INDEX UNIQ_7B8331130403B5E');
        $this->addSql('DROP INDEX UNIQ_7B8331188FC5C3B');
        $this->addSql('DROP INDEX UNIQ_7B833119A49F3D5');
        $this->addSql('DROP INDEX UNIQ_7B8331122F594B0');
        $this->addSql('DROP INDEX UNIQ_7B833117A9684E6');
        $this->addSql('DROP INDEX UNIQ_7B83311C22AE383');
        $this->addSql('DROP INDEX UNIQ_7B83311D027019');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja25_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja26_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja27_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja28_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja29_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja30_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja31_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja32_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja33_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja34_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja35_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja36_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja37_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja38_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja39_id');
        $this->addSql('ALTER TABLE hurtowe DROP kompozycja40_id');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk25');
        $this->addSql('ALTER TABLE hurtowe DROP cena25');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc25');
        $this->addSql('ALTER TABLE hurtowe DROP wozek25');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa25');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk26');
        $this->addSql('ALTER TABLE hurtowe DROP cena26');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc26');
        $this->addSql('ALTER TABLE hurtowe DROP wozek26');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa26');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk27');
        $this->addSql('ALTER TABLE hurtowe DROP cena27');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc27');
        $this->addSql('ALTER TABLE hurtowe DROP wozek27');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa27');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk28');
        $this->addSql('ALTER TABLE hurtowe DROP cena28');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc28');
        $this->addSql('ALTER TABLE hurtowe DROP wozek28');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa28');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk29');
        $this->addSql('ALTER TABLE hurtowe DROP cena29');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc29');
        $this->addSql('ALTER TABLE hurtowe DROP wozek29');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa29');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk30');
        $this->addSql('ALTER TABLE hurtowe DROP cena30');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc30');
        $this->addSql('ALTER TABLE hurtowe DROP wozek30');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa30');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk31');
        $this->addSql('ALTER TABLE hurtowe DROP cena31');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc31');
        $this->addSql('ALTER TABLE hurtowe DROP wozek31');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa31');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk32');
        $this->addSql('ALTER TABLE hurtowe DROP cena32');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc32');
        $this->addSql('ALTER TABLE hurtowe DROP wozek32');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa32');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk33');
        $this->addSql('ALTER TABLE hurtowe DROP cena33');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc33');
        $this->addSql('ALTER TABLE hurtowe DROP wozek33');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa33');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk34');
        $this->addSql('ALTER TABLE hurtowe DROP cena34');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc34');
        $this->addSql('ALTER TABLE hurtowe DROP wozek34');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa34');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk35');
        $this->addSql('ALTER TABLE hurtowe DROP cena35');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc35');
        $this->addSql('ALTER TABLE hurtowe DROP wozek35');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa35');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk36');
        $this->addSql('ALTER TABLE hurtowe DROP cena36');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc36');
        $this->addSql('ALTER TABLE hurtowe DROP wozek36');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa36');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk37');
        $this->addSql('ALTER TABLE hurtowe DROP cena37');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc37');
        $this->addSql('ALTER TABLE hurtowe DROP wozek37');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa37');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk38');
        $this->addSql('ALTER TABLE hurtowe DROP cena38');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc38');
        $this->addSql('ALTER TABLE hurtowe DROP wozek38');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa38');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk39');
        $this->addSql('ALTER TABLE hurtowe DROP cena39');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc39');
        $this->addSql('ALTER TABLE hurtowe DROP wozek39');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa39');
        $this->addSql('ALTER TABLE hurtowe DROP sztuk40');
        $this->addSql('ALTER TABLE hurtowe DROP cena40');
        $this->addSql('ALTER TABLE hurtowe DROP wartosc40');
        $this->addSql('ALTER TABLE hurtowe DROP wozek40');
        $this->addSql('ALTER TABLE hurtowe DROP nazwa40');
    }
}
