controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index

app_get_hurtowe_wozek:
    path: /admin/hurtowe/{id}/wozek/{wozek}
    controller: App\Controller\Admin\HurtoweWozekController::getHurtoweWozek

app_get_hurtowe_wozek_pdf:
    path: /admin/hurtowe-pdf/{id}/wozek/{wozek}
    controller: App\Controller\Admin\HurtoweWozekController::getHurtoweWozekPdf

app_get_hurtowe_zamowienie:
    path: /admin/hurtowe/{id}
    controller: App\Controller\Admin\HurtoweWozekController::getHurtoweZamowienie
    requirements:
        id: '\d+'

app_get_hurtowe_zamowienie_pdf:
    path: /admin/hurtowe-pdf/{id}
    controller: App\Controller\Admin\HurtoweWozekController::getHurtoweZamowieniePdf

fv_krok_1:
    path: /admin/fv_krok_1/{id}
    controller: App\Controller\Admin\HurtoweWozekController::getHurtoweZamowienieFvKrok1
    requirements:
        id: '\d+'

fv_krok_2:
    path: /admin/fv_krok_2/{id}
    controller: App\Controller\Admin\HurtoweWozekController::getHurtoweZamowienieFvBeforeApi
    requirements:
        id: '\d+'

fv_krok_3:
    path: /admin/fv_krok_3/{id}
    controller: App\Controller\Admin\HurtoweWozekController::getHurtoweZamowienieFvPreview
    requirements:
        id: '\d+'

fv_krok_4:
    path: /admin/fv_krok_4/{id}
    controller: App\Controller\Admin\HurtoweWozekController::sendToFakturaXL
    requirements:
        id: '\d+'

app_get_zeszyt_zestawienie:
    path: /admin/zeszyt/{id}/zestawienie/{zestawienie}
    controller: App\Controller\Admin\ZeszytZestawienieController::getZeszytZestawienie

app_get_zeszyt_zestawienie_pdf:
    path: /admin/zeszyt-pdf/{id}/zestawienie/{zestawienie}
    controller: App\Controller\Admin\ZeszytZestawienieController::getZeszytZestawieniePdf

app_get_zeszyt_zamowienie:
    path: /admin/zeszyt/{id}
    controller: App\Controller\Admin\ZeszytZestawienieController::getZeszytZamowienie

app_get_zeszyt_zamowienie_pdf:
    path: /admin/zeszyt-pdf/{id}
    controller: App\Controller\Admin\ZeszytZestawienieController::getZeszytZamowieniePdf
