<?php

namespace tests\Controller\Admin;

use App\Controller\Admin\PolproduktyCrudController;
use App\Entity\Polprodukty;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\TestCase;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class PolproduktyCrudControllerTest extends KernelTestCase
{
    private $entityManager;
protected function setUp(): void
{

    parent::setUp(); // TODO: Change the autogenerated stub
    $kernel = self::bootKernel();

    $this->entityManager = $kernel->getContainer()->get('doctrine')->getManager();

}

    public function testAddAndReadPolprodukt(){

    $polprodukt = new Polprodukty();
    $polprodukt->setNazwa('Kaktusidlo2');
    $polprodukt->setCena(10);

//
//        $this->entityManager->persist($polprodukt);
//        $this->entityManager->flush();


        $loadedProduct = $this->entityManager
            ->getRepository(Polprodukty::class)
            ->findOneBy(['nazwa' => 'Kaktusidlo2']);

//dd($loadedProduct);

        $this->assertSame('Kaktusidlo2', $loadedProduct->getNazwa());
        $this->assertSame(10.0, $loadedProduct->getCena());

        return 'cos';
}

}
